### ISSUE TITLE
My Todo

### ISSUE THREAD

**Issue by collabH** [collabH/bigdata-growth#5]
**2021 Plan3**
- [x] 1. hudi相关学习，案例、demo、cdc落湖 
- [x] 2. flink cdc 2.x 深入学习，对比1.x的改变等。 
- [x] 3. rocksdb反复学习，思考olap中应用参数优化。

**Comment by collabH** [comment]
**2022 Plan1**
- [x] 1. alluxio学习，包含概念、快速上手、与计算引擎整合等 
- [x] 2. flink亚洲大会ppt学习
- [x] 产出一篇偏实践的Hudi实践公众号文章

**Comment by collabH** [comment]
- [ ] 产出一篇偏事件的Hudi实践公众号文章
